// Mocks generated by Mockito 5.4.2 from annotations
// in clean_architecture/test/features/random_activity/data/repositories/random_activity_respository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:clean_architecture/core/connection/network_info.dart' as _i6;
import 'package:clean_architecture/features/random_activity/data/datasource/random_activity_local_data_source.dart'
    as _i5;
import 'package:clean_architecture/features/random_activity/data/datasource/random_activity_remote_data_source.dart'
    as _i3;
import 'package:clean_architecture/features/random_activity/data/models/random_activity_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRandomActivityModel_0 extends _i1.SmartFake
    implements _i2.RandomActivityModel {
  _FakeRandomActivityModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RandomActivityRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomActivityRemoteDataSource extends _i1.Mock
    implements _i3.RandomActivityRemoteDataSource {
  MockRandomActivityRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RandomActivityModel> getRandomActivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomActivity,
          [],
        ),
        returnValue: _i4.Future<_i2.RandomActivityModel>.value(
            _FakeRandomActivityModel_0(
          this,
          Invocation.method(
            #getRandomActivity,
            [],
          ),
        )),
      ) as _i4.Future<_i2.RandomActivityModel>);
}

/// A class which mocks [RandomActivityLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomActivityLocalDataSource extends _i1.Mock
    implements _i5.RandomActivityLocalDataSource {
  MockRandomActivityLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void>? cacheRandomActivity(
          _i2.RandomActivityModel? activityToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheRandomActivity,
          [activityToCache],
        ),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>?);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }
}
